name: openkarateapp
description: app description

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  about: ^1.2.0
  animations: ^1.1.2
  auto_route: ^0.6.9
  auto_size_text: ^2.1.0
  bloc: ^6.1.0
  carousel_slider: ^2.1.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  equatable: ^1.2.5
  expandable: ^4.1.4
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.0
  flutter_markdown: ^0.5.1
  flutter_secure_storage: ^3.3.5
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hydrated_bloc: ^6.0.3
  intl: ^0.16.1
  json_annotation: ^3.0.0
  jwt_decoder: ^1.0.3
  logger: ^0.9.2
  open_file: ^3.0.3
  path: ^1.6.4
  path_provider: ^1.6.24
  pedantic: ^1.9.2
  permission_handler: ^5.0.1+1
  replay_bloc: ^0.0.1-dev.3
  responsive_framework: ^0.0.14
  retrofit: any
  share: ">=0.6.5+4 <2.0.0"
  strings: ^0.1.4
  styled_widget: ^0.2.2
  table_calendar: ^2.2.3
  url_launcher: ^5.7.2
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: any
  auto_route_generator: ^0.6.10
  bloc_test: ^7.1.0
  build_config: ^0.4.3
  build_runner: ^1.10.6
  build_runner_core: ^6.1.1
  flutter_launcher_icons: ^0.8.1
  hive_generator: any
  json_serializable: ^3.2.0
  mockito: ^4.1.1
  retrofit_generator: ^1.4.0
  source_gen: ^0.9.8
  test: ^1.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # ignore asset_directory_does_not_exist
    - google_fonts/
    - assets/images/icon/
    - assets/images/
    - assets/CHANGELOG.md
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
